export const ACTIONS = {
   FETCH_ITEMS_REQUEST:   'FETCH_ITEMS_REQUEST',
   FETCH_ITEMS_SUCCESS:   'FETCH_ITEMS_SUCCESS',
   FETCH_ITEMS_ERROR:     'FETCH_ITEMS_FAILED',

   ADD_DASHBOARD_ITEM:    'ADD_DASHBOARD_ITEM',
   UPDATE_DASHBOARD_ITEM: 'UPDATE_DASHBOARD_ITEM',
   EXPAND_DASHBOARD_ITEM: 'EXPAND_DASHBOARD_ITEM',
};
